
spring:
  datasource:
    password: 19082003!Nan!Andrei!David!
    url: jdbc:mysql://127.0.0.1:3306/serversdb
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

